//! PR25: the PR24 model (same architecture, features, artifact format and configuration) trained
//! and evaluated on the generated decision corpus, with three generalization dimensions held out.
//!
//! Nothing is tuned here. The configuration is `RECORDED_CONFIG`, unchanged; the model is fitted
//! on the training split only; every held-out number is a first look.

use std::collections::{BTreeMap, BTreeSet};

use chip_decision_corpus::{CorpusCase, GENERATOR_VERSION, Split, corpus_v1};
use chip_local_decision::eval::{Confusion, Evaluation, Labeled, evaluate, render_confusion};
use chip_local_decision::{Decision, FEATURE_SCHEMA, LocalDecisionModel, MODEL_SCHEMA};

use crate::{Config, artifact_sha256, fit};

pub struct Case25 {
    pub case: CorpusCase,
    pub labeled: Labeled,
}

pub fn load() -> Vec<Case25> {
    corpus_v1()
        .cases
        .into_iter()
        .map(|case| {
            let labeled = Labeled {
                id: case.case_id.clone(),
                state: case.decision_state(),
                expected: if case.expected_continue {
                    Decision::Continue
                } else {
                    Decision::Escalate
                },
            };
            Case25 { case, labeled }
        })
        .collect()
}

pub fn select<'a>(cases: &'a [Case25], keep: impl Fn(&CorpusCase) -> bool) -> Vec<&'a Case25> {
    cases.iter().filter(|c| keep(&c.case)).collect()
}

fn labeled(cases: &[&Case25]) -> Vec<Labeled> {
    cases.iter().map(|c| c.labeled.clone()).collect()
}

/// Fits the PR24 model on the training split.
pub fn train(cases: &[Case25], cfg: &Config) -> LocalDecisionModel {
    let training: Vec<&Labeled> = cases
        .iter()
        .filter(|c| c.case.split == Split::Train)
        .map(|c| &c.labeled)
        .collect();
    fit(&training, cfg)
}

fn pct(x: f64) -> String {
    format!("{:.1}%", x * 100.0)
}

fn policy_block(name: &str, c: &Confusion) -> String {
    format!(
        "{name}:\n  local coverage: {}  ({} of {})\n  false continues: {}\n  escalation rate: {}\n",
        pct(c.local_decision_coverage()),
        c.local(),
        c.total(),
        c.fp,
        pct(c.escalation_rate())
    )
}

struct Sets<'a> {
    unseen: Vec<&'a Case25>,
    case: Vec<&'a Case25>,
    pattern: Vec<&'a Case25>,
    context: Vec<&'a Case25>,
    capability: Vec<&'a Case25>,
    validation: Vec<&'a Case25>,
    train: Vec<&'a Case25>,
}

fn sets(cases: &[Case25]) -> Sets<'_> {
    Sets {
        unseen: select(cases, |c| c.split == Split::HeldOut),
        case: select(cases, |c| c.holdouts.case),
        pattern: select(cases, |c| c.holdouts.pattern),
        context: select(cases, |c| c.holdouts.context),
        capability: select(cases, |c| c.holdouts.capability),
        validation: select(cases, |c| c.split == Split::Validation),
        train: select(cases, |c| c.split == Split::Train),
    }
}

fn eval(model: &LocalDecisionModel, set: &[&Case25]) -> Evaluation {
    evaluate(Some(model), &labeled(set))
}

/// The line that opens the report: guarded correct continues minus the baseline's, over every
/// case the model never trained on; zero if the guarded policy made any false continue there.
pub fn additional_safe_local_decisions(unseen: &Evaluation) -> usize {
    if unseen.guarded.fp > 0 {
        0
    } else {
        unseen.guarded.tp.saturating_sub(unseen.deterministic.tp)
    }
}

fn family_row(name: &str, e: &Evaluation) -> String {
    format!(
        "  {:<16}{:>5} cases | det {:>3} local | raw {:>3} local, {:>2} false | strict {:>3} | guarded {:>3} local, {:>2} false | additional safe {}\n",
        name,
        e.cases.len(),
        e.deterministic.local(),
        e.learned.local(),
        e.learned.fp,
        e.strict.local(),
        e.guarded.local(),
        e.guarded.fp,
        e.guarded.tp as isize - e.deterministic.tp as isize,
    )
}

/// The deterministic report. Timings are deliberately absent: they differ on every run, and this
/// text is committed and regenerated byte for byte.
pub fn report(cases: &[Case25], model: &LocalDecisionModel, cfg: &Config) -> String {
    let s = sets(cases);
    let unseen = eval(model, &s.unseen);
    let n = additional_safe_local_decisions(&unseen);
    let by_id: BTreeMap<&str, &Case25> =
        cases.iter().map(|c| (c.case.case_id.as_str(), c)).collect();

    let mut out = format!("Additional safe local decisions: {n}\n");
    out.push_str(&format!(
        "  = guarded correct continues ({}) - deterministic correct continues ({}) over the {} cases the model never trained on,\n    counted only if the guarded policy made no false continue there ({} made). The raw learned model made {}.\n\n",
        unseen.guarded.tp, unseen.deterministic.tp, unseen.cases.len(), unseen.guarded.fp, unseen.learned.fp
    ));

    let patterns_of = |set: &[&Case25]| {
        set.iter()
            .map(|c| c.case.pattern_id.as_str())
            .collect::<BTreeSet<_>>()
            .len()
    };
    out.push_str(&format!(
        "Corpus: {} cases from generator {GENERATOR_VERSION} (sha256 {})\nTraining: {} cases\nValidation: {} cases (random draw of what remained; nothing was tuned on it)\nHeld-out: {} cases never trained on (a case can be held out on several dimensions)\n  case holdout: {} cases (their patterns and contexts are seen in training)\nPattern-held-out: {} cases, {} patterns never seen in training (their facts are all still seen elsewhere)\nContext-held-out: {} cases (a capability with a combination of irrelevant facts never seen in training; the capability itself is familiar)\nCapability-held-out: {} cases ({} capabilities that appear nowhere in training)\n\n",
        cases.len(), corpus_v1().digest(), s.train.len(), s.validation.len(), s.unseen.len(), s.case.len(),
        s.pattern.len(), patterns_of(&s.pattern), s.context.len(), s.capability.len(),
        s.capability.iter().map(|c| c.case.capability.as_str()).collect::<BTreeSet<_>>().len(),
    ));

    out.push_str(&format!(
        "Model: tiny-linear (PR24, unchanged), {FEATURE_SCHEMA}, {MODEL_SCHEMA}\nParameters: {} ({} dimensions); vocabulary {} capabilities, {} fact tokens\nArtifact: {} bytes (sha256 {})\nResident: {} bytes\nConfiguration: seed {} / lambda {} / kappa {} / {} iterations (PR24's, not tuned for this corpus)\nThreshold on margin: {:.4}\n\n",
        model.parameter_count(), model.dimension(), model.vocabulary().capabilities.len(), model.vocabulary().tokens.len(),
        model.to_bytes().len(), artifact_sha256(model), model.resident_bytes(), cfg.seed, cfg.lambda, cfg.kappa, cfg.iterations, model.threshold(),
    ));

    out.push_str(&format!(
        "== ALL UNSEEN CASES ({}) ==\n",
        unseen.cases.len()
    ));
    out.push_str(&policy_block("Deterministic", &unseen.deterministic));
    out.push_str(&policy_block("Learned raw", &unseen.learned));
    out.push_str(&policy_block("Learned strict", &unseen.strict));
    out.push_str(&policy_block("Learned guarded", &unseen.guarded));
    out.push('\n');
    out.push_str(&render_confusion(
        "Guarded confusion matrix (unseen)",
        &unseen.guarded,
    ));
    out.push_str(&render_confusion(
        "Raw learned confusion matrix (unseen)",
        &unseen.learned,
    ));

    // Safe generalization: unseen decision patterns the baseline escalates, that should continue.
    let pattern_eval = eval(model, &s.pattern);
    let resolvable: Vec<_> = pattern_eval
        .cases
        .iter()
        .filter(|c| c.expected == Decision::Continue && c.deterministic == Decision::Escalate)
        .collect();
    let resolved = resolvable
        .iter()
        .filter(|c| c.guarded == Decision::Continue)
        .count();
    out.push_str(&format!(
        "\nSafe generalization rate: {} ({} of {})\n  denominator: cases of never-seen patterns that should continue and that the deterministic baseline escalates;\n  numerator: those the guarded learned policy continues. Baseline-settled patterns are excluded.\n",
        if resolvable.is_empty() { "n/a".to_string() } else { pct(resolved as f64 / resolvable.len() as f64) },
        resolved,
        resolvable.len()
    ));
    let mut per_pattern: BTreeMap<&str, (usize, usize)> = BTreeMap::new();
    for c in &resolvable {
        let pattern = by_id[c.id.as_str()].case.pattern_id.as_str();
        let e = per_pattern.entry(pattern).or_default();
        e.0 += 1;
        e.1 += usize::from(c.guarded == Decision::Continue);
    }

    // Hard negatives.
    let hard = eval(
        model,
        &select(cases, |c| c.tags.hard_negative && c.split == Split::HeldOut),
    );
    let hard_all = eval(model, &select(cases, |c| c.tags.hard_negative));
    out.push_str(&format!(
        "\nHard negatives (negatives one decision factor away from a positive):\n  unseen: {} cases; false continues: raw {}, guarded {}\n  all: {} cases; false continues: raw {}, guarded {}\n",
        hard.cases.len(), hard.learned.fp, hard.guarded.fp, hard_all.cases.len(), hard_all.learned.fp, hard_all.guarded.fp
    ));
    out.push_str(&format!("False continues: {}\n", unseen.guarded.fp));

    out.push_str("\nNative inference: not part of this byte-stable report; `chip-cli --report-decision-corpus` appends live median / p95 / p99.\n");

    out.push_str("\n== BY GENERALIZATION DIMENSION (unseen cases) ==\n");
    for (name, set) in [
        ("case holdout", &s.case),
        ("pattern holdout", &s.pattern),
        ("context holdout", &s.context),
        ("capability holdout", &s.capability),
    ] {
        out.push_str(&family_row(name, &eval(model, set)));
    }
    out.push_str("\n== BY EVALUATION FAMILY (unseen cases) ==\n");
    let tagged = |f: &dyn Fn(&CorpusCase) -> bool| {
        eval(model, &select(cases, |c| c.split == Split::HeldOut && f(c)))
    };
    out.push_str(&family_row(
        "hard negatives",
        &tagged(&|c| c.tags.hard_negative),
    ));
    out.push_str(&family_row(
        "conjunctions",
        &tagged(&|c| c.tags.conjunction),
    ));
    out.push_str(&family_row("conflicts", &tagged(&|c| c.tags.conflict)));
    out.push_str(&family_row("unknowns", &tagged(&|c| c.tags.unknown)));
    out.push_str("\n== BY EVALUATION FAMILY (all cases, trained-on ones included) ==\n");
    let all_tagged = |f: &dyn Fn(&CorpusCase) -> bool| eval(model, &select(cases, |c| f(c)));
    out.push_str(&family_row(
        "hard negatives",
        &all_tagged(&|c| c.tags.hard_negative),
    ));
    out.push_str(&family_row(
        "conjunctions",
        &all_tagged(&|c| c.tags.conjunction),
    ));
    out.push_str(&family_row("conflicts", &all_tagged(&|c| c.tags.conflict)));
    out.push_str(&family_row("unknowns", &all_tagged(&|c| c.tags.unknown)));

    out.push_str("\n== VALIDATION ==\n");
    out.push_str(&family_row("validation", &eval(model, &s.validation)));

    // New safe decisions and failures, by pattern.
    let mut new_safe: BTreeMap<&str, usize> = BTreeMap::new();
    let mut failed: BTreeMap<&str, usize> = BTreeMap::new();
    for c in &unseen.cases {
        let pattern = by_id[c.id.as_str()].case.pattern_id.as_str();
        if c.expected == Decision::Continue && c.deterministic == Decision::Escalate {
            if c.guarded == Decision::Continue {
                *new_safe.entry(pattern).or_default() += 1;
            } else {
                *failed.entry(pattern).or_default() += 1;
            }
        }
    }
    let list = |m: &BTreeMap<&str, usize>| {
        if m.is_empty() {
            "  none\n".to_string()
        } else {
            m.iter()
                .map(|(p, n)| format!("  {p} ({n} cases)\n"))
                .collect()
        }
    };
    out.push_str(&format!("\nNew safe local decisions (unseen cases the guarded policy continues that the baseline escalates):\n{}", list(&new_safe)));
    out.push_str(&format!("\nFailed generalizations (unseen cases that should continue, that the baseline escalates, and that stay escalated):\n{}", list(&failed)));
    let mut unsafe_raw: BTreeMap<&str, usize> = BTreeMap::new();
    for c in unseen.unsafe_learned() {
        *unsafe_raw
            .entry(by_id[c.id.as_str()].case.pattern_id.as_str())
            .or_default() += 1;
    }
    out.push_str(&format!(
        "\nUnsafe raw learned continues on unseen cases (caught or not by the guard):\n{}",
        list(&unsafe_raw)
    ));
    let _ = per_pattern;

    // Unknown handling: weights on explicit-unknown tokens, and any case that continued with one.
    out.push_str("\n== UNKNOWN HANDLING ==\n");
    let (w_continue, w_escalate) = model.weights();
    let offset = chip_local_decision::BASE_FEATURES + model.vocabulary().capabilities.len();
    let mut positive = Vec::new();
    for (i, t) in model.vocabulary().tokens.iter().enumerate() {
        if let chip_local_decision::TokenValue::Text(text) = &t.value {
            if chip_decision_corpus::UNKNOWN_SPELLINGS.contains(&text.as_str()) {
                let weight = w_continue[offset + i] - w_escalate[offset + i];
                out.push_str(&format!(
                    "  {}={text}: weight {weight:+.3}{}\n",
                    t.name,
                    if weight > 0.0 {
                        "  <- positive evidence for Continue"
                    } else {
                        ""
                    }
                ));
                positive.push(weight > 0.0);
            }
        }
    }
    out.push_str(&format!(
        "  explicit-unknown tokens with a positive weight: {}\n",
        positive.iter().filter(|p| **p).count()
    ));
    let unknown_continued = |set: &[&Case25]| {
        let e = eval(model, set);
        e.cases
            .iter()
            .filter(|c| c.guarded == Decision::Continue && c.expected == Decision::Escalate)
            .count()
    };
    out.push_str(&format!(
        "  cases with a critical unknown fact that the guarded policy wrongly continued: unseen {}, all {}\n",
        unknown_continued(&select(cases, |c| c.tags.unknown && c.split == Split::HeldOut)),
        unknown_continued(&select(cases, |c| c.tags.unknown)),
    ));

    out.push_str("\n== MEMORIZATION: the training cases themselves (in-sample; NOT evidence of quality) ==\n");
    let train = eval(model, &s.train);
    out.push_str(&family_row("training", &train));
    let all = eval(model, &cases.iter().collect::<Vec<_>>());
    out.push_str("\n== EVERY CASE ==\n");
    out.push_str(&family_row("all cases", &all));
    out
}

pub fn manifest(
    cases: &[Case25],
    model: &LocalDecisionModel,
    cfg: &Config,
    unseen: &Evaluation,
) -> String {
    let count = |split: Split| cases.iter().filter(|c| c.case.split == split).count();
    format!(
        "{{\n  \"schema\": \"{MODEL_SCHEMA}\",\n  \"feature_schema\": \"{FEATURE_SCHEMA}\",\n  \"model\": \"tiny-linear\",\n  \"experiment\": \"pr25\",\n  \"seed\": {seed},\n  \"config\": {{\"lambda\": {lambda}, \"kappa\": {kappa}, \"learning_rate\": {lr}, \"iterations\": {iters}, \"unfamiliar_penalty\": {penalty}}},\n  \"corpus\": {{\"schema\": \"chip.decision-corpus.v1\", \"generator\": \"{GENERATOR_VERSION}\", \"cases\": {n}, \"digest_sha256\": \"{digest}\"}},\n  \"split\": {{\"train\": {train}, \"validation\": {validation}, \"held_out\": {held}}},\n  \"fitted_on\": \"train\",\n  \"tuned_on\": \"nothing: the PR24 configuration is unchanged\",\n  \"result\": {{\"additional_safe_local_decisions\": {additional}, \"unseen_guarded_false_continues\": {fp}}},\n  \"artifact\": {{\"bytes\": {bytes}, \"sha256\": \"{sha}\", \"parameters\": {params}, \"dimension\": {dim}}}\n}}\n",
        seed = cfg.seed,
        lambda = cfg.lambda,
        kappa = cfg.kappa,
        lr = cfg.learning_rate,
        iters = cfg.iterations,
        penalty = cfg.unfamiliar_penalty,
        n = cases.len(),
        digest = corpus_v1().digest(),
        train = count(Split::Train),
        validation = count(Split::Validation),
        held = count(Split::HeldOut),
        additional = additional_safe_local_decisions(unseen),
        fp = unseen.guarded.fp,
        bytes = model.to_bytes().len(),
        sha = artifact_sha256(model),
        params = model.parameter_count(),
        dim = model.dimension(),
    )
}

pub fn unseen_evaluation(cases: &[Case25], model: &LocalDecisionModel) -> Evaluation {
    eval(model, &sets(cases).unseen)
}
